{% set name = "nbstripout" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b997c99b8bbb865988202d2f005cdaabb2598b07dad891c302a147a5871a4a95

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - nbstripout = nbstripout:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - pytest-runner
  run:
    - python

test:
  requires:
    - nbformat
  imports:
    - nbstripout
  commands:
    - nbstripout --help

# Not running tests since pytest-cram and pytest-flake8 are not yet conda packaged

# test:
#   source_files:
#     - tests
#   requires:
#     - pytest
#     - pytest-flake8
#     - pytest-cram
#   commands:
#     - python setup.py test

about:
  home: https://github.com/kynan/nbstripout
  license: MIT
  license_family: MIT
  # FIXME: need to add to MANIFEST.in
  # license_file: LICENSE.txt
  summary: 'strip output from Jupyter and IPython notebooks'
  description: |
    Opens a notebook, strips its output, and writes the outputless version to the
    original file.

    Useful mainly as a git filter or pre-commit hook for users who don't want to
    track output in VCS.

    This does mostly the same thing as the `Clear All Output` command in the
    notebook UI.
  doc_url: https://pypi.org/project/nbstripout/
  dev_url: https://github.com/kynan/nbstripout

extra:
  recipe-maintainers:
    - kynan
