travis:
  secure:
    BINSTAR_TOKEN: hVZFxaaepH951Q8L5oDJ94P/xsH7rM5DOuLpyIthHmv1ZRn861EH4M0zMhFpPgzw4U+AJ43kMnvI+muG/1Rkw+78eBVTvoL0WYyR70q6aRY9L4TKa0qDzfysSdVnSOoWClRny/vcMfg8d1vNNkNT1v0+wD2+ZL+zz+psAgLdPsLEDGrNN0ha88/n8Fzi4gZMoadDj8Vg1+YdHKJB1jrcJyvx89OQrolTmQViy9f7EiAkC3PfyNLYckVuMlTxGPxr2VoX5f974DZydqHV///MqNfbL+8c8s0IiNRFHcogDzzDpSmDDoQ4sLkOEWgc9HDhQrzdHxrCOcDdQZRNGLQqGSiSgGIDayZyUYyaVRCOXna9XxSx2FF8ZcCmEKhdJtvB+t+Y+hbtKKMFgvL48XTcSeLWk+J0102ctL1jAtVw73hxMgAAvSWt8m94IBpzek5hE0RaRUOLFQ7EV/CH4QBMYb/ccAhqfS6ogFM38WjMXwwIqshqCIcVf95+9x1k93ESiBvR8EycGMwTAzWM+IcKTaB56ceGikKFUtR+WU+ZPkRqiKZ/0vxkvZrMDkwPT5XcjXL8h70p8KgXxLPu91tT4r8W9VD+5qXNb1OL2nm9C1kL+NrB/ISsusEsgaRNwA1LXVTZ2mMD645E7p/2phMN+gb9JV5U6wwy+VVyw1kP424=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
