travis:
  secure:
    BINSTAR_TOKEN: YUHtOPFzTgwf/7KXbezTSENnX83jgoqtnjtWQwRSrmmxd4fqAskw1wpALFtDWpTvxaYuPWFoxjyMQyBeLdauRzqJtsQnV8lsnJ1D0BnhQl5nQciqBBNlZsVR/Gzr/OQnz9FLvzw3LCWcXqsLlnhZoDW2rVL9PgyB8rVk0SETifpRv8+qqmbEZqeOdtr3ENEvFBHlo+4JMvoU1pfSjlbQL6zOSXejZz3no7sal+W0VGQkTxdPZer4D9/0hb2UOsjRj2VOCLBOkAk9kG/OXUmfclXtKHE7q5CZTiyp4yRL6/mI2/4Py7ic97micqMcm1q67ItAKCE3sZcCEtnA54hq5fc+juSBTjHifOhXjILg9ZDFrR43xGkj8E7M0o2dvMQrZK2YagruEx1cn1VvXK1RjYxeZtya0ocHuLlGUCr4TdLQfppPLNC+p+ISjMcmVuCTFOUR1fUirlBzbECMRmVi063nCc6EPL5JBpiEvCaZaG8qLsoLsrmcKJDe85LPr6hz+j4vcaP2v/8AzP30FIgBKFcKrg6tErc/st+f9F6/zZ3WTxTAP5c8CZVdZDJ/GIsYwVjM5A97cWNgjw7VS2SC3NZQRBfW2dKBMDY4V+meW8+GHCmU1tBVufstYokGZtVMmWbOPqB/yMnDNzmN1Cuv85ZWIJnmWHfzFJAPC8L06GQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
