travis:
  secure:
    BINSTAR_TOKEN: UUVFxWTz2QFv4u91Q/HeG2WYEdc3KGC4JL/5GNXzQTVYpIZrVXc4253r9xdrb1spkSFHvjBPhQuOq4FYh9BDGjgy3VyIRbJLE9NusIjFttaUug+OhyD1mCZ15WhYe2h0CwAHrrhU/EV6A84vAg3JlHUIx7u2Y7LfkfS1bXne+1yii8Oq+RBenFSYZ3ewxZQ69Xyfa10Ltb1gFj7aEQo0sJabzJEhMFq1dVJLlBRH9A4tNRcMh+3/ACkod/0I+QSjBnvwhCRtME7skbnCZwulJ0NHjFV0/ENuEebwkA1o2+ZXfnzGluOZo/J/EARNIlAawzg5iJkMliRqysZ7BJkJ+NsBEhBbB8Q98DV9Xagq6zb9OAuoRJ0JBtzFrDcjoa0N9G/hZ0OYorG6idT0/On1g0n7jn/YJPQ4WnT1JdC8yrDZoueacaf9kwgaDzWgsm6MpoYhI2b7GBGFTkS2d+UFS4QV9fjOfT3/QL5nM6gXr2F7scbpMhq0V7ZBbc80ACv8O7fkpZ66CT1l6IGr8mcz3Kd7HOcEpMM7l+ZUVLo3Oqvn6SRdGeGdvsXuABlkykG9/H/BFIt+4PJ7y1Hgg+RdPCliS/h4JEWli91XgJ0jXxHvL1SOg7V1qgrDURIZ3BWaa80N+LlTjwl5FLq/u9qhYQfPHDsFD9ruoac+UmXn7AE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
